### ISSUE TITLE
bug(abci): We are updating the entire valset every block (this is big bad).

### ISSUE THREAD

**Issue by itsdevbear** [berachain/beacon-kit#1095]

**Comment by abi87** [comment]
Solved in two parts:

- https://github.com/berachain/beacon-kit/pull/2142 stops updating validators at each block (it does every epoch)
- https://github.com/berachain/beacon-kit/pull/2143 sends only diffs

**Comment by abi87** [comment]
Solved by https://github.com/berachain/beacon-kit/pull/2142
