### ISSUE TITLE
beacond suggested-fee-recipient address flag not working

### ISSUE THREAD

**Issue by NodeKing** [berachain/beacon-kit#1407]
When using the `beacond` binary with the  `--beacon-kit.builder.suggested-fee-recipient` flag it doesn't work. Not a huge issue as setting it in the app.toml file instead works fine, just a FYI.

**Comment by ocnc2** [comment]
addressed by https://github.com/berachain/beacon-kit/pull/1415

Suggested fee recipient now set using the following flag:
`--beacon-kit.payload-builder.suggested-fee-recipient`
