### ISSUE TITLE
beacond doesn't honor `config.toml:priv_validator_key_file` path for signing blocks

### ISSUE THREAD

**Issue by jmo-staked** [berachain/beacon-kit#1513]
problem: our validator node would start up with the correct identity, report in the logs it was a validator, but upon trying to submit a block for validation we get the error:
```text
2024-06-17T18:37:27.856345127Z stdout F {"level":"error","module":"server","module":"baseapp","height":403750,"time":"2024-06-17T18:37:26Z","err":"expected signature length 96, got 64: signer returned an invalid signature","time":"2024-06-17T18:37:27Z","message":"failed to prepare proposal"}
```

### Issues
1) the function `ProvideBlsSigner` has a hardcoded path to look for your private key at `homeDir+"/config/priv_validator_key.json"`, overriding the value of `config.toml:priv_validator_key_file`
* https://github.com/berachain/beacon-kit/blob/main/mod/node-core/pkg/components/signer.go#L40-L51

@po-bera actually flagged this as a problem on the initial PR review:
* https://github.com/berachain/beacon-kit/pull/513/files#r1523154257

2) In the block signing code the  function`NewBLSSigner` uses the method `privval.LoadOrGenFilePV(keyFilePath, stateFilePath)`. And since `keyFilePath` from issue 1 selects what can be a non-existant, hardcoded path, the method `.LoadOrGenFilePV` _silently_ creates a new private key at `homeDir+"/config/priv_validator_key.json` and attempts to sign blocks with that _second_ private key. This conflicts with the validator identity `beacond` is setting via `config.toml:priv_validator_key_file`

* https://github.com/berachain/beacon-kit/blob/main/mod/node-core/pkg/components/signer/signer.go#L38-L41

Silently creating a second pair of private keys instead of just erroring out if no keys are found also seems like a somewhat dangerous choice for validator operation

### Workaround
For anyone hitting this issue our ugly workaround is to run this command before node startup:

```bash
cp -a <config.toml:priv_validator_key_file> ${BEACOND_HOME}/config/priv_validator_key.json
```

**Comment by archbear** [comment]
closed by #1526
