### ISSUE TITLE
Wrong absolute key path (v0.2.0-alpha.2)

### ISSUE THREAD

**Issue by MattKetmo** [berachain/beacon-kit#1671]
Hello,

We're loading validator keys from Vault, using an in-memory mount piont on `/vault/secrets` (via vault-injector)

To make it work, the `config.toml` looks like this:

```
node_key_file = '/vault/secrets/node_key.json'
priv_validator_key_file = '/vault/secrets/priv_validator_key.json'
```

However, it appends the path to the app home **instead of using an absolute path**, which causes the node to crash.
```
berachain open /home/app/.beacond/vault/secrets/priv_validator_key.json: no such file or directory
```

Concerned version: `v0.2.0-alpha.2`

Thanks

**Comment by nidhi-singh02** [comment]
https://github.com/berachain/beacon-kit/pull/1722

**Comment by nidhi-singh02** [comment]
@MattKetmo  The PR has been merged, Could you please test it using the mount point and LMK the outcome.
@itsdevbear @ocnc I think it could be verified by building binary `make build` until we cut the release.

**Comment by itsdevbear** [comment]
@MattKetmo let us know if this solves your issue and we will close the issue :)

**Comment by MattKetmo** [comment]
tested locally, looks like it works yes 👍 
thx

**Comment by itsdevbear** [comment]
awesome @MattKetmo feel free to keep running main, it's stable
