### ISSUE TITLE
Beacond restart loop

### ISSUE THREAD

**Issue by ncavedale-xlabs** [berachain/beacon-kit#2029]
Hi team!
I deployed a testnet RPC node which was catching up fine. However `beacond` suddenly began showing this error and restarting every 30secs or so:
```
Sep 20 00:34:47 beacond[1783388]: 2024-09-20T00:34:47Z ERRR Error in proxyAppConn.FinalizeBlock module=state err=A timeout occurred while waiting for final validator updates: context deadline exceeded
Sep 20 00:34:47 beacond[1783388]: panic: Failed to process committed block (4880125:8BBBD5AEAC49C71E0AEFC3A98EFF5DCA71B12C971C9D605988F7B62141264472): A timeout occurred while waiting for final validator updates: context deadline exceeded
Sep 20 00:34:47 beacond[1783388]: goroutine 4879 [running]:
Sep 20 00:34:47 beacond[1783388]: github.com/cometbft/cometbft/internal/blocksync.(*Reactor).poolRoutine(0xc00328e008, 0x0)
Sep 20 00:34:47 beacond[1783388]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/blocksync/reactor.go:551 +0x1845
Sep 20 00:34:47 beacond[1783388]: github.com/cometbft/cometbft/internal/blocksync.(*Reactor).OnStart.func1()
Sep 20 00:34:47 beacond[1783388]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/blocksync/reactor.go:139 +0x4e
Sep 20 00:34:47 beacond[1783388]: created by github.com/cometbft/cometbft/internal/blocksync.(*Reactor).OnStart in goroutine 1
Sep 20 00:34:47 beacond[1783388]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/blocksync/reactor.go:137 +0x8b
Sep 20 00:34:47 systemd[1]: beacond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 20 00:34:47 systemd[1]: beacond.service: Failed with result 'exit-code'.
Sep 20 00:34:47 systemd[1]: beacond.service: Consumed 12.791s CPU time.
```

The execution client (`reth`) is getting new blocks in between `beacond` restarts, but is obviously going very slow because of this. The same thing happened to me about one or two weeks ago, and the issue seems to have resolved by itself, but this is not ideal because the node keeps falling behind. In this case, it's already been 3 or 4 days with `beacond` getting restarted constantly.

FYI the block showing the error (4880125:8BBBD5AEAC49C71E0AEFC3A98EFF5DCA71B12C971C9D605988F7B62141264472) is different every time.

I'm running these versions:
- beacon: "v0.2.0-alpha.8"
- reth: "v1.0.6"

**Comment by abi87** [comment]
Hello @ncavedale-xlabs, thanks for your issue.
From your logs, it looks like Beacon-Kit has failed storing a finalized block while bootstrapping, which caused CometBFT consensus to panic.
The failure is due to an internal timeout (see https://github.com/berachain/beacon-kit/blob/5bdacfc04edb5172ccf362397e09ca07af0c469f/mod/consensus/pkg/cometbft/service/middleware/constants.go#L33)

While we look for the cleanest way to solve this, could you consider patching your binary by extending this timeout and testing whether panics happen again? Depending on your machine, even setting timeout to 3 seconds could be enough to make the panic disappear.

**Comment by abi87** [comment]
Thanks @ncavedale-xlabs.
I am going to close this for the time being. Feel free to open another issue should the situation present itself again.

**Comment by ncavedale-xlabs** [comment]
sounds good! btw the patched binary is working fine so far 👌

**Comment by jiangjinyuan** [comment]
> sounds good! btw the patched binary is working fine so far 👌

Hi, I got the issue with beacon: "v0.2.0-alpha.8" too. Which patched binary you are using now?
