### ISSUE TITLE
Bartio Snapshots endpoint is down - How can we get the snapshots?

### ISSUE THREAD

**Issue by andreclaro** [berachain/beacon-kit#2091]
Hello Berachain team,

Bartio Snapshots endpoint is currently down: https://storage.googleapis.com/bartio-snapshot/index.html

![image](https://github.com/user-attachments/assets/1d343be4-e5ef-45e9-b030-7e8290ed72e9)

How can we get the snapshots?

Thanks

**Comment by gummybera** [comment]
Hi Andre - we're working on a few infra updates, it will be restored shortly. In the meantime please feel free to grab a snapshot from any of these other providers: https://github.com/chuck-bear/awesome-berachain-validators/blob/main/README.md#snapshots
