### ISSUE TITLE
Create-validator cli is broken since alpha.5

### ISSUE THREAD

**Issue by chuck-bear** [berachain/beacon-kit#2122]
The create-validator CLI is broken since alpha.5, last time it worked it was with alpha.4.

How to reproduce it ?

Run that command line with alpha.8 binary:
```
beacond deposit create-validator $VAL_WITHDRAW_CREDENTIAL $VAL_DEPOSIT_GWEI_AMOUNT $GENESIS_FORK_VERSION $GENESIS_VALIDATORS_ROOT --private-key $YOUR_ETH_WALLET_PRIVATE_KEY  --home $YOUR_BEACON_HOME_DIR
```
It will return `open : no such file or directory`

And run it with alpha.4 binary.

Let me know if you need more details.

**Comment by chuck-bear** [comment]
Thanks @dezzeus this looks very familiar to https://github.com/berachain/beacon-kit/issues/2123

**Comment by abi87** [comment]
@chuck-bear we do have a proposed solution by @dezzeus on https://github.com/berachain/beacon-kit/pull/2128. Can you try it out?

**Comment by chuck-bear** [comment]
@dezzeus @abi87 just tested, it's working. Thanks!
