### ISSUE TITLE
Beacon client online, but no consensus updates received

### ISSUE THREAD

**Issue by ncavedale-xlabs** [berachain/beacon-kit#2141]
Hi team!
Every now and then, the node stops syncing with the following message in `geth` logs:
```
Oct 30 20:36:14 geth[248526]: WARN [10-30|20:36:14.391] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
```

And I don't see anything unusual in the `beacon` logs. The solution is to simply restart the `beacond` service. It starts working fine after that.

Were you aware of this?
Perhaps there's a beacon config setting that can help in these cases?

**Comment by chuck-bear** [comment]
We might need more information here. is that a fresh install? Is that a node using a snapshot? What's the beacond version?

But first, can you compare your beacon config with the toml files listed here: https://github.com/berachain/beacon-kit/tree/main/testing/networks/80084

**Comment by ncavedale-xlabs** [comment]
This is not a fresh install, but it has also happened before when we were running `reth` (we're running `geth` now).
We used a snapshot for `beacon` but not for `geth`. The `beacon` version is "v0.2.0-alpha.8".
I compared the .toml files: the `config.toml` is the same we're already using, but there are some differences in `app.toml`:

`app.toml` in repo:
- rpc-timeout = "900ms"
- rpc-jwt-refresh-interval = "20s"

`app.toml` in our server:
- rpc-timeout = "2s"
- rpc-jwt-refresh-interval = "30s"

Also noticed that sections like "API Configuration" and "gRPC Configuration" are no longer present, so I can try using a new copy of `app.toml` to see if that helps.

FYI, we're also running with a patched binary: https://github.com/berachain/beacon-kit/issues/2029

**Comment by chuck-bear** [comment]
This is a known issue:
`rpc-timeout = "2s"`

**Comment by chuck-bear** [comment]
And you issue was linked to the rpc-timeout, no need to run a patched version.

**Comment by ncavedale-xlabs** [comment]
The default timeout (on code) was 2s, and by patching the binary we increased it to 3s. If I set it to 900ms like in `app.toml`, wouldn't that cause the issue to reappear?

In any case, that was a different issue where `beacon` would restart over and over again. Our current issue however, seems to be a stop in the communication between `beacon` and `geth`/`reth`. What would you suggest for this?

**Comment by ncavedale-xlabs** [comment]
Node has been running fine for the past week, so I'm closing this issue. Thanks!
