### ISSUE TITLE
Determine optimal solution for keeping track of sorted validator set by balance

### ISSUE THREAD

**Issue by calbera** [berachain/beacon-kit#2151]
Can sort in 2 diff ways:
- Either only when evicting the lowest stake validator as done in https://github.com/berachain/beacon-kit/pull/2119
- OR Keeping the sorted validators set by stake in the BeaconState itself (will require O(logN) work on addition, but O(1) on eviction)

**Comment by abi87** [comment]
Addressed by https://github.com/berachain/beacon-kit/pull/2226
